import os
from pathlib import Path


class iWebServerBaseConfig:
    # log
    IWEBSERVER_LOG_DIR = os.environ.get('IWEBSERVER_LOG_DIR', Path(__file__).resolve().parent.parent.parent)
    IWEBSERVER_APP_DEBUG = True if (os.environ.get('IWEBSERVER_APP_DEBUG', 'False') == 'True') else False
    IWEBSERVER_REQUEST_RECORD_ENABLE = True if (os.environ.get('IWEBSERVER_REQUEST_RECORD_ENABLE', 'False') == 'True') else False

    # mysql
    IWEBSERVER_DB_MYSQL_DBNAME = os.environ.get('IWEBSERVER_DB_MYSQL_DBNAME')
    IWEBSERVER_DB_MYSQL_HOST = os.environ.get('IWEBSERVER_DB_MYSQL_HOST')
    IWEBSERVER_DB_MYSQL_PORT = os.environ.get('IWEBSERVER_DB_MYSQL_PORT')
    IWEBSERVER_DB_MYSQL_USER = os.environ.get('IWEBSERVER_DB_MYSQL_USER')
    IWEBSERVER_DB_MYSQL_PASSWORD = os.environ.get('IWEBSERVER_DB_MYSQL_PASSWORD')

    # mqtt
    IWEBSERVER_MQTT_SERVER_LIST = os.environ.get('IWEBSERVER_MQTT_SERVER_LIST', '')
    IWEBSERVER_MQTT_USERNAME = os.environ.get('IWEBSERVER_MQTT_USERNAME', 'admin')
    IWEBSERVER_MQTT_PASSWORD = os.environ.get('IWEBSERVER_MQTT_PASSWORD', '1XPv7QEjiL')
    IWEBSERVER_MQTT_TLS_ENABLE = True if (os.environ.get('IWEBSERVER_MQTT_TLS_ENABLE', 'False') == 'True') else False
    IWEBSERVER_MQTT_TLS_CA_PATH = os.environ.get('IWEBSERVER_MQTT_TLS_CA_PATH', '/home/yang/idms/bin/ca/ca.crt')
    IWEBSERVER_MQTT_TLS_CERT_PATH = os.environ.get('IWEBSERVER_MQTT_TLS_CERT_PATH', '/home/yang/idms/bin/ca/client.crt')
    IWEBSERVER_MQTT_TLS_PRIVATE_KEY_PATH = os.environ.get('IWEBSERVER_MQTT_TLS_PRIVATE_KEY_PATH', '/home/yang/idms/bin/ca/client.key')
    IWEBSERVER_MQTT_TLS_PORT = os.environ.get('IWEBSERVER_MQTT_TLS_PORT', '')


    # jwt
    IWEBSERVER_JWT_ACCESS_TOKEN_LIFETIME_DAYS = os.environ.get('IWEBSERVER_JWT_ACCESS_TOKEN_LIFETIME_DAYS', '7')
    IWEBSERVER_JWT_ACCESS_TOKEN_LIFETIME_SECONDS = os.environ.get('IWEBSERVER_JWT_ACCESS_TOKEN_LIFETIME_SECONDS', '0')
    IWEBSERVER_JWT_ACCESS_TOKEN_LIFETIME_HOURS = os.environ.get('IWEBSERVER_JWT_ACCESS_TOKEN_LIFETIME_HOURS', '0')
    IWEBSERVER_JWT_ACCESS_TOKEN_LIFETIME_MINUTES = os.environ.get('IWEBSERVER_JWT_ACCESS_TOKEN_LIFETIME_MINUTES', '0')
    IWEBSERVER_JWT_ACCESS_TOKEN_LIFETIME_WEEKS = os.environ.get('IWEBSERVER_JWT_ACCESS_TOKEN_LIFETIME_WEEKS', '0')

    # permission
    IWEBSERVER_PERMISSION_ADMIN_ACCESS = 'all_access'
    IWEBSERVER_PERMISSION_REGULAR_ACCESS = 'regular_access'

    # Error Code
    IWEBSERVER_ERROR_CODE_USER_NOT_PRESENCED = -101
    IWEBSERVER_ERROR_CODE_INVALID_PASSWORD = -102
    IWEBSERVER_ERROR_CODE_NO_ADMIN_PERMISSION = -103
    IWEBSERVER_ERROR_CODE_INVALID_PARAS = -104
    IWEBSERVER_ERROR_CODE_SERVER_INTERNAL_ERROR = -105
    IWEBSERVER_ERROR_CODE_INVALID_REFRESH_TOKEN = -106
