import os
from pathlib import Path


class iWebServerBaseConfig:
    # log
    IWEBSERVER_LOG_DIR = os.environ.get('IWEBSERVER_LOG_DIR', Path(__file__).resolve().parent.parent.parent)
    IWEBSERVER_APP_DEBUG = True if (os.environ.get('IWEBSERVER_APP_DEBUG', 'False') == 'True') else False

    # mysql
    IWEBSERVER_DB_MYSQL_DBNAME = os.environ.get('IWEBSERVER_DB_MYSQL_DBNAME')
    IWEBSERVER_DB_MYSQL_HOST = os.environ.get('IWEBSERVER_DB_MYSQL_HOST')
    IWEBSERVER_DB_MYSQL_PORT = os.environ.get('IWEBSERVER_DB_MYSQL_PORT')
    IWEBSERVER_DB_MYSQL_USER = os.environ.get('IWEBSERVER_DB_MYSQL_USER')
    IWEBSERVER_DB_MYSQL_PASSWORD = os.environ.get('IWEBSERVER_DB_MYSQL_PASSWORD')

    # jwt
    IWEBSERVER_JWT_ACCESS_TOKEN_LIFETIME_DAYS = os.environ.get('IWEBSERVER_JWT_ACCESS_TOKEN_LIFETIME_DAYS', '7')
    IWEBSERVER_JWT_ACCESS_TOKEN_LIFETIME_SECONDS = os.environ.get('IWEBSERVER_JWT_ACCESS_TOKEN_LIFETIME_SECONDS', '0')
    IWEBSERVER_JWT_ACCESS_TOKEN_LIFETIME_HOURS = os.environ.get('IWEBSERVER_JWT_ACCESS_TOKEN_LIFETIME_HOURS', '0')
    IWEBSERVER_JWT_ACCESS_TOKEN_LIFETIME_MINUTES = os.environ.get('IWEBSERVER_JWT_ACCESS_TOKEN_LIFETIME_MINUTES', '0')
    IWEBSERVER_JWT_ACCESS_TOKEN_LIFETIME_WEEKS = os.environ.get('IWEBSERVER_JWT_ACCESS_TOKEN_LIFETIME_WEEKS', '0')

    # permission
    IWEBSERVER_PERMISSION_ADMIN_ACCESS = 'all_access'
    IWEBSERVER_PERMISSION_REGULAR_ACCESS = 'regular_access'
    IWEBSERVER_PERMISSION_WORKSTATION_ACCESS = 'workstation_access'
    IWEBSERVER_PERMISSION_ROOM_ACCESS = 'room_access'


