import os

from interface.datatype.config import iWebServerBaseConfig


class iWebServerConfig(iWebServerBaseConfig):
    # You can customize the desired configuration here

    # permission
    IWEBSERVER_PERMISSION_WORKSTATION_ACCESS = 'workstation_access'
    IWEBSERVER_PERMISSION_ROOM_ACCESS = 'room_access'

    # Error Code
    IWEBSERVER_ERROR_CODE_EMAIL_ALREADY_PRESENCED = -1107
    IWEBSERVER_ERROR_CODE_USERNAME_ALREADY_PRESENCED = -1108
    IWEBSERVER_ERROR_CODE_PASSWORD_NOT_MATCH = -1109
    IWEBSERVER_ERROR_CODE_CHANGING_ADMIN_USER = -1110
    IWEBSERVER_ERROR_CODE_WORKSTATION_ALREADY_PRESENCED = -1111
    IWEBSERVER_ERROR_CODE_WORKSTATION_NOT_PRESENCED = -1112
    IWEBSERVER_ERROR_CODE_ROOM_ALREADY_PRESENCED = -1113
    IWEBSERVER_ERROR_CODE_ROOM_NOT_PRESENCED = -1114
    IWEBSERVER_ERROR_CODE_CREATE_ROOM_FAILED = -1115

    # janus
    IWEBSERVER_JANUS_BASE_URL = os.environ.get('IWEBSERVER_JANUS_BASE_URL')
